### ISSUE TITLE
mc_rtc_ticker segmentation fault

### ISSUE THREAD

**Issue by micco00x** [jrl-umi3218/mc_rtc_ros#14]
Good morning,

I have installed mc_rtc by following the installation guide provided on the website (I'm using Ubuntu 18.04 with ROS Melodic) and I am trying to go through the Tutorials to understand how to write a controller using the framework. However, I'm stuck at the beginning: I'm trying to run a simple controller (the default one specified in the mc_rtc.yaml files provided during the installation), with the following commands (https://jrl-umi3218.github.io/mc_rtc/tutorials/introduction/running-a-controller.html):
```bash
$ roslaunch mc_rtc_ticker display.launch
$ rosrun mc_rtc_ticker mc_rtc_ticker
```
What I am experiencing is that the first program works, while the second one gives me the following:
```
[info] Loading default global configuration /usr/local/etc/mc_rtc.yaml
[info] Loading additional global configuration "/home/michele/.config/mc_rtc/mc_rtc.yaml"
[info] Enabled plugins: ROS (autoload)
[info] GUI server enabled
[info] Will serve data on:
[info] - ipc:///tmp/mc_rtc_pub.ipc
[info] - tcp://*:4242
[info] Will handle requests on:
[info] - ipc:///tmp/mc_rtc_rep.ipc
[info] - tcp://*:4343
[info] Loading additional plugin configuration: "/usr/local/lib/mc_plugins/etc/ROS.yaml"
Segmentation fault (core dumped)
```
Any idea on how to fix this issue? Let me know if you need any additional information.

Thank you in advance.

**Comment by gergondet** [comment]
Hi @micco00x 

Thanks for trying out mc_rtc.

From the log it seems you follow the source installation path (i.e. you run the build_and_install script?), it seems to segfault very early.

Are you familiar with gdb? Can you run mc_rtc_ticker in gdb and report the backtrace?

If you are not, here's a quick guide to get what we need to have more information:

```bash
rosrun --prefix 'gdb -ex run --args' mc_rtc_ticker mc_rtc_ticker
```

This will load mc_rtc_ticker in gdb. Type `r` in the command prompt that will appear. After the segfault occurs, type `bt` to get the backtrace and copy the output here.

**Comment by micco00x** [comment]
Hi, thanks for the quick reply.

I actually though I had a problem with Ubuntu so I tried to install everything again on a brand new version of the OS and mc_rtc_ticker is now running perfectly. I probably had a clash with an old version of mc_rtc.
