### ISSUE TITLE
Can't add any task from rviz panel

### ISSUE THREAD

**Issue by rohanpsingh** [jrl-umi3218/mc_rtc_ros#25]
@gergondet

It seems that something is broken in the mc_rtc rviz panel.  
When we try to add a task (say mc_tasks::EndEffectorTask) from the rviz panel, we get a "type must be completed" pop up error.  
Image for reference:  

![Screenshot from 2021-08-19 19-45-48](https://user-images.githubusercontent.com/16384313/130056364-f357f418-0fd2-4a29-97d5-277fe1e4528f.png)

**Comment by gergondet** [comment]
@rohanpsingh this is definitely an mc_rtc_ros bug, I have transferred the issue there

I think you pinpointed the right commit. I will look into it, should have a fix very soon
