### ISSUE TITLE
mc_log_visualization

### ISSUE THREAD

**Issue by Saeed-Mansouri** [jrl-umi3218/mc_rtc_ros#4]
Hi,

After running `roslaunch mc_log_visualization log_visualizer.launch robot:=sm_r_v1 log:=/tmp/mc-control-MyController-latest.bin`, I have seen this error:
 
> No entry named t in the loaded log

Do you know what the problem is?

Thanks,

**Comment by gergondet** [comment]
Hi @Saeed-Mansouri,

The log might be empty. Can you open the log with `mc_log_ui` ? What's the size of the log file?

**Comment by arntanguy** [comment]
Closing now, feel free to reopen if you're still facing this issue in the future.
