### ISSUE TITLE
How to Execute Controller Without mc_rtc_ticker in Updated mc_rtc_ros

### ISSUE THREAD

**Issue by Saeed-Mansouri** [jrl-umi3218/mc_rtc_ros#44]
Hello,

I am currently working with an older version of `mc_rtc_ros` which includes `mc_rtc_ticker.cpp`. To run the controller, I have been using the command `rosrun mc_rtc_ticker mc_rtc_ticker`. I noticed that in the latest version of `mc_rtc_ros`, `mc_rtc_ticker.cpp` and potentially other modules have been integrated directly into `mc_rtc`.

Could you please provide guidance on how to run the controller using the new structure of `mc_rtc_ros`? Specifically, I am interested in understanding which component of `mc_rtc` now fulfills the role previously handled by `mc_rtc_ticker`, especially regarding ticking the controller at each step time.

Thank you for your assistance.

**Comment by arntanguy** [comment]
In the latest version of `mc_rtc`, `rosrun mc_rtc_ticker mc_rtc_ticker` has been replaced by the executable `mc_rtc_ticker` installed by `mc_rtc` itself. It provides the same features as its ros counterpart (the `ROS` plugin of `mc_rtc` is the one responsible for publishing all relevant robot state).

So simply update `mc_rtc` and run
```sh
mc_rtc_ticker
````
